# 第4章 2次元配列



2次元配列arrの内容を表示して下さい．

In [8]:
arr = [
    [1, 2, 3],
    [4, 5, 6],
]

print(arr)

for i in range(len(arr)):
    for j in range(len(arr[0])):
        print(arr[i][j], end='')
    print('')

[[1, 2, 3], [4, 5, 6]]
123
456


In [6]:
import numpy as np

n_arr = np.array(arr)
print(n_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2次元配列n_arrの内容を表示して下さい．

In [14]:
for i in range(len(n_arr)):
    for j in range(len(n_arr[0])):
        print(n_arr[i][j], end='')
    print('')

123
456
789


DataFrameを表示して下さい

行を抽出して下さい．

列を抽出して下さい．